# Generated by Django 2.2.12 on 2020-05-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='splits_km',
            field=models.FloatField(default=0),
        ),
    ]
