# Generated by Django 2.2.13 on 2020-07-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20200525_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='kml_creator',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='tcx_creator',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
