# Generated by Django 2.2.12 on 2020-04-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20200421_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackdetail',
            name='_accuracy',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_alt_rolling',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_alts',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_bearing',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_calories',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_computed_dist',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_computed_dist_smooth',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_computed_dist_smooth2',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_computed_dist_smooth3',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_computed_speed',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_computed_speed_rolling',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_computed_speed_smooth',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_computed_speed_smooth2',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_computed_speed_smooth3',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_delta_times',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_delta_times_string',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_dist_csv',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_dist_tcx',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_frequencies',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_frequency_rolling',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_heartbeat_rolling',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_heartbeats',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_laps_indices',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_lats',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_long',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_segment_indices',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_slope_rolling',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_smooth2_indices',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_smooth3_indices',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_smooth_indices',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_speed_csv',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_speed_rolling',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_split_indices',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_step_length_rolling',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_subtrack_indices',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_times',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_times_string',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_times_string_nodate',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='trackdetail',
            name='_vertical_speed_rolling',
            field=models.TextField(default='[]', null=True),
        ),
    ]
