# Generated by Django 2.2.12 on 2020-04-25 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20200425_2256'),
        ('tracks', '0003_auto_20200421_2136'),
    ]

    operations = [
    ]
