# Generated by Django 2.2.13 on 2020-07-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_track_gpx_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='photos_details',
            field=models.CharField(blank=True, default='No linking performed yet', max_length=512, null=True),
        ),
    ]
