# Generated by Django 2.2.13 on 2020-08-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_track_photos_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='segment_names',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='subtrack_names',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
