# Generated by Django 2.2.13 on 2021-05-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0007_auto_20200901_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='ascii_name',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Ascii name'),
        ),
    ]
