# Generated by Django 2.2.13 on 2021-05-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0008_track_ascii_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='priority',
            field=models.IntegerField(default=5),
        ),
    ]
