# Generated by Django 2.2.25 on 2022-02-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0009_track_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='activity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
