# Generated by Django 2.2.25 on 2022-02-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0010_auto_20220220_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='garmin_info',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
