# Generated by Django 2.2.7 on 2020-04-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoJsonObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True, verbose_name='Object Name')),
                ('geojson', models.TextField(blank=True, null=True, verbose_name='GeoJSON')),
                ('website', models.TextField(blank=True, null=True, verbose_name='Website address')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Date of modification')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of creation')),
                ('is_global', models.BooleanField(default=False, verbose_name='Shown on all maps')),
                ('is_valid', models.CharField(default='', max_length=10, verbose_name='Is valid GeoJSON')),
                ('errors', models.TextField(blank=True, null=True, verbose_name='GeoJSON validation errors')),
                ('min_lat', models.FloatField(blank=True, null=True)),
                ('min_lon', models.FloatField(blank=True, null=True)),
                ('max_lat', models.FloatField(blank=True, null=True)),
                ('max_lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'GeoJsonObject',
                'ordering': ['pk'],
            },
        ),
    ]
