# Generated by Django 2.2.13 on 2020-06-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geojson_obj', '0002_geojsonobject_feature_for_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojsonobject',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Is valid GeoJSON'),
        ),
    ]
