# Generated by Django 2.2.13 on 2020-07-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_auto_20200512_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionset',
            name='DEFAULT_LAT',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='<h3>Default centering for maps</h3> Default Latitude'),
        ),
        migrations.AddField(
            model_name='optionset',
            name='DEFAULT_LNG',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Default Longitude'),
        ),
    ]
