# Generated by Django 2.2.13 on 2021-05-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_auto_20200710_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionset',
            name='TOMTOM_FILENAME',
            field=models.CharField(blank=True, default='1.zip', max_length=200, null=True, verbose_name='TomTom file name, see https://mysports.tomtom.com/app/settings/account-manage/data-protection/'),
        ),
    ]
