# Generated by Django 2.2.12 on 2020-04-25 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_auto_20200421_2100'),
        ('options', '0004_auto_20200425_2256'),
    ]

    operations = [
    ]
