# Generated by Django 2.2.24 on 2021-12-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0006_optionset_photos_download_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionset',
            name='GARMIN_PASSWORD',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Garmin password'),
        ),
        migrations.AddField(
            model_name='optionset',
            name='GARMIN_USER',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='<h3> Garmin </h3> Garmin username'),
        ),
    ]
