# Generated by Django 2.2.24 on 2022-01-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0009_track_priority'),
        ('waypoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='other_tracks',
            field=models.ManyToManyField(blank=True, related_name='other_tracks', to='tracks.Track'),
        ),
    ]
