version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6.1
      - image: circleci/postgres:10.3
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python manage.py test
          name: Test
          environment:
            DB_HOST: localhost
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_NAME: gps_tracks_test

workflows:
  main:
    jobs:
      - build-and-test

