# Generated by Django 2.2.12 on 2020-04-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=512, unique=True, verbose_name='File name')),
                ('comment', models.CharField(blank=True, max_length=512, null=True, verbose_name='Comment')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Date of modification')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of creation')),
                ('files', models.TextField(blank=True, null=True, verbose_name='Associated files')),
                ('interpret_regex', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Blacklist',
                'ordering': ['pk'],
            },
        ),
    ]
