# Generated by Django 2.2.13 on 2020-07-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='method',
            field=models.CharField(choices=[['Exact match', 'Exact match'], ['Contains', 'Contains'], ['Regex', 'Regex']], default='Contains', max_length=15, verbose_name='Method of comparison'),
        ),
    ]
