# Generated by Django 2.2.13 on 2020-07-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='interpret_regex',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='method',
            field=models.CharField(choices=[['Exact', 'Exact'], ['Contains', 'Contains'], ['Regex', 'Regex']], default='Exact', max_length=15, verbose_name='Method of comparison'),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='number_matched_files',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='comment',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='file_name',
            field=models.CharField(max_length=512, verbose_name='File name'),
        ),
    ]
