# Generated by Django 2.2.13 on 2020-07-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklists', '0002_blacklist_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='file_name',
            field=models.CharField(max_length=512, verbose_name='File name'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='method',
            field=models.CharField(choices=[['Exact match', 'Exact match'], ['Contains', 'Contains'], ['Regex', 'Regex']], default='Exact Match', max_length=15, verbose_name='Method of comparison'),
        ),
    ]
