# Generated by Django 2.2.13 on 2020-07-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklists', '0005_auto_20200728_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='number_matched_tracks',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
