# Generated by Django 2.2.13 on 2020-07-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklists', '0006_blacklist_number_matched_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='comment',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Comment'),
        ),
    ]
