# Generated by Django 2.2.13 on 2020-07-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklists', '0007_auto_20200730_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
