# Generated by Django 2.2.13 on 2020-07-30 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacklists', '0008_blacklist_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='number_matched_tracks',
            new_name='number_matched_files',
        ),
    ]
