# Generated by Django 2.2.13 on 2020-07-31 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacklists', '0009_auto_20200730_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='interpret_regex',
        ),
    ]
