# Generated by Django 2.2.13 on 2020-09-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='deduced_alt',
            field=models.FloatField(default=None, null=True),
        ),
    ]
