# Generated by Django 2.2.24 on 2021-09-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_deduced_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='deduced_alt',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='deduced_lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='deduced_long',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='track_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
