# Generated by Django 2.2.12 on 2020-04-26 14:52
# modified by hand to accomodate the USE_TEXT_INSTEAD_OF_ARRAYS option

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    fields = [
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
        ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of creation')),
        ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Date of modification')),
        ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
        ('created_by_hand', models.BooleanField(default=True, verbose_name='Created by hand')),
        ('beg_country', models.CharField(blank=True, default='', max_length=50, null=True)),
        ('beg_region', models.CharField(blank=True, default='', max_length=100, null=True)),
        ('beg_city', models.CharField(blank=True, default='', max_length=50, null=True)),
        ('beg_address', models.CharField(blank=True, default='', max_length=250, null=True)),
        ('end_country', models.CharField(blank=True, default='', max_length=50, null=True)),
        ('end_region', models.CharField(blank=True, default='', max_length=100, null=True)),
        ('end_city', models.CharField(blank=True, default='', max_length=50, null=True)),
        ('end_address', models.CharField(blank=True, default='', max_length=250, null=True)),
        ('lats_text', models.TextField(blank=True, default='[]', null=True, verbose_name='Lats')),
        ('long_text', models.TextField(blank=True, default='[]', null=True, verbose_name='Long')),
        ('alts_text', models.TextField(blank=True, default='[]', null=True, verbose_name='Alts')),
        ('total_length', models.FloatField(blank=True, null=True)),
        ('closed', models.BooleanField(default=False, verbose_name='Make first and last point coincide')),
        ('n_points', models.IntegerField(default=0, null=True)),
        ('line_type', models.CharField(blank=True, choices=[('path', 'Path'), ('border', 'Border'), ('canal', 'Canal'), ('river', 'River'), ('other', 'Other')], max_length=255, null=True, verbose_name='Type')),
        ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Color')),
        ('is_global', models.BooleanField(default=True, verbose_name='Shown on all maps')),
        ('min_lat', models.FloatField(null=True)),
        ('max_lat', models.FloatField(null=True)),
        ('min_long', models.FloatField(null=True)),
        ('max_long', models.FloatField(null=True)),
    ]

    from django.conf import settings
    if settings.USE_TEXT_INSTEAD_OF_ARRAYS:
        fields.extend([
            ('_lats', models.TextField( null=True, default=("[]"))),
            ('_long', models.TextField( null=True, default=("[]"))),
            ('_alts', models.TextField( null=True, default=("[]"))),
            ('_lengths', models.TextField( null=True, default=("[]"))),
        ])
    else:
        fields.extend([
            ('_lats', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, null=True, size=None)),
            ('_long', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, null=True, size=None)),
            ('_alts', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, null=True, size=None)),
            ('_lengths', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, null=True, size=None)),
        ])

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=fields,
            options={
                'verbose_name': 'Line',
                'ordering': ['pk'],
            },
        ),
    ]
