# Generated by Django 2.2.12 on 2020-04-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0002_line_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='alts',
        ),
        migrations.RemoveField(
            model_name='line',
            name='lats',
        ),
        migrations.RemoveField(
            model_name='line',
            name='lengths',
        ),
        migrations.RemoveField(
            model_name='line',
            name='long',
        ),
    ]
