# Generated by Django 2.2.12 on 2020-04-25 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0002_line_track'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='line',
        #     old_name='alts',
        #     new_name='_alts',
        # ),
        # migrations.RenameField(
        #     model_name='line',
        #     old_name='lats',
        #     new_name='_lats',
        # ),
        # migrations.RenameField(
        #     model_name='line',
        #     old_name='lengths',
        #     new_name='_lengths',
        # ),
        # migrations.RenameField(
        #     model_name='line',
        #     old_name='long',
        #     new_name='_long',
        # ),
    ]
