# Generated by Django 2.2.12 on 2020-04-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0004_merge_20200425_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='alts',
        ),
        migrations.RemoveField(
            model_name='line',
            name='lats',
        ),
        migrations.RemoveField(
            model_name='line',
            name='lengths',
        ),
        migrations.RemoveField(
            model_name='line',
            name='long',
        ),
        migrations.AddField(
            model_name='line',
            name='_alts',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='_lats',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='_lengths',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='_long',
            field=models.TextField(default='[]', null=True),
        ),
    ]
