# Generated by Django 2.2.7 on 2020-04-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='tracks.Track'),
        ),
    ]
