# Generated by Django 2.2.13 on 2020-07-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_tracks'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('query_string', models.TextField(blank=True, default='?', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='rules_act_as_and',
            field=models.BooleanField(default=True, verbose_name='Take intersection of rules (instead of union)'),
        ),
        migrations.AddField(
            model_name='group',
            name='rules',
            field=models.ManyToManyField(blank=True, to='groups.GroupRule'),
        ),
    ]
