# Generated by Django 2.2.12 on 2020-04-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='w_lats',
        ),
        migrations.RemoveField(
            model_name='group',
            name='w_long',
        ),
        migrations.RemoveField(
            model_name='group',
            name='w_names',
        ),
    ]
