# Generated by Django 2.2.13 on 2021-06-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20200701_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tracks_priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Default priority to assign to tracks'),
        ),
    ]
