# Generated by Django 2.2.13 on 2021-06-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Import Step Name')),
                ('step_code', models.CharField(max_length=255, unique=True)),
                ('step_type', models.CharField(choices=[('11_download_tracks', 'Download Tracks'), ('21_import_tracks', 'Import Tracks'), ('31_download_photos', 'Download Photos'), ('41_import_photos', 'Import Photos'), ('51_link_track_photos', 'Link Photos to Tracks')], max_length=255)),
            ],
            options={
                'ordering': ['step_type'],
            },
        ),
        migrations.CreateModel(
            name='QuickImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Quick Import Name')),
                ('active', models.BooleanField(blank=True, default=True)),
                ('steps', models.ManyToManyField(blank=True, to='quick_import.ImportStep')),
            ],
        ),
    ]
