# Generated by Django 2.2.25 on 2022-03-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_import', '0002_steps_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importstep',
            name='step_type',
            field=models.CharField(choices=[('11_download_tracks', 'Download Tracks'), ('21_import_tracks', 'Import Tracks'), ('31_download_photos', 'Download Photos'), ('41_import_photos', 'Import Photos'), ('51_link_track_photos', 'Link Photos to Tracks'), ('52_link_all_track_photos', 'Link Photos to all Tracks'), ('53_link_track_all_photos', 'Link all Photos to Tracks')], max_length=255),
        ),
    ]
