# Generated by Django 2.2.7 on 2020-04-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infos', models.TextField(blank=True, default='', null=True, verbose_name='Infos')),
                ('warnings', models.TextField(blank=True, default='', null=True, verbose_name='Errors')),
                ('errors', models.TextField(blank=True, default='', null=True, verbose_name='Errors')),
            ],
            options={
                'verbose_name': 'Log',
                'ordering': ['pk'],
            },
        ),
    ]
